# Data Preprocessing Tools

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [25]:
data_set = pd.read_csv("Data.csv")
X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

In [5]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [6]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [26]:
from sklearn.impute import SimpleImputer
# Identify missing data (assumes that missing data is represented as NaN)
missing_data = data_set.isnull().sum()
print("Missing data: \n", missing_data)
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

Missing data: 
 Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


In [8]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [0])], remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [28]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [15]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

In [17]:
print(X_train)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]]


In [18]:
print(X_test)

[[0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [20]:
print(y_train)

[0 0 1 1 1 0 0 1]


In [21]:
print(y_test)

[0 1]


## Feature Scaling

In [30]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train[:, -3:] = scaler.fit_transform(X_train[:, -3:])
X_test[:, -3:] = scaler.transform(X_test[:, -3:])

In [31]:
print(X_train)

[[1.0 0.0 -0.7745966692414834 0.963227856626714 1.004126756924506]
 [0.0 1.0 -0.7745966692414834 -1.2284960248173662 -0.8210461420574847]
 [0.0 0.0 1.2909944487358056 -1.6981511422696691 -1.429437108384815]
 [1.0 0.0 -0.7745966692414834 -0.13263408409532615 0.4971342849850642]
 [1.0 0.0 -0.7745966692414834 1.5894346798964512 1.7139162176397247]
 [0.0 0.0 1.2909944487358056 0.023917621722108144 -0.11125668134226609]
 [0.0 0.0 1.2909944487358056 0.14568005958011274 -1.0238431308332614]
 [0.0 1.0 -0.7745966692414834 0.33702103335697675 0.17040580306853528]]


In [32]:
print(X_test)

[[0.0 1.0 -0.7745966692414834 1.9025380915313197 2.1195101951912783]
 [1.0 0.0 -0.7745966692414834 -0.4457374957301948 -0.4154521645059312]]
